/-!
# A basis-free replacement for the mod-7 image argument

`ModSevenImage.lean` proves that the standard transvection `T = [[1,1],[0,1]]` and the
companion matrix `C` of a Frobenius characteristic polynomial generate a group of order
`336 = |SL_2(F_7)|`.  External review observed that this does not by itself settle the
image, because the basis putting inertia into the form `T` need not be the basis putting
Frobenius into the form `C`: the actual Frobenius `g` is only *conjugate* to `C`.

This file removes the dependence on any choice of basis.  It proves, with no imports
beyond `Init`:

* `irreducible_moves_every_line`: a matrix over `F_7` whose characteristic polynomial is
  irreducible fixes no line.  Hence for a transvection `T` with fixed line `L`, the
  conjugate `g T g⁻¹` is a transvection with fixed line `g L ≠ L`.
* `sl2_transitive_on_distinct_pairs`: `SL_2(F_7)` acts transitively on ordered pairs of
  distinct lines, so such a pair may be moved to `(⟨e₁⟩, ⟨e₂⟩)`.
* `normalized_pairs_generate`: for every `a, b ≠ 0`, the transvections `[[1,a],[0,1]]`
  and `[[1,0],[b,1]]` generate all of `SL_2(F_7)`.

Together these say: *whenever the image contains a nontrivial transvection and a matrix
with irreducible characteristic polynomial, it contains `SL_2(F_7)`* -- with no choice of
basis anywhere.  Nothing here depends on which matrices the arithmetic produces.

Encoding: a matrix is the index `a + 7b + 49c + 343d` in `[0, 2401)`; a subgroup is the
bit set of a natural number; closures are fuel-bounded fixpoints checked by the kernel.
-/

set_option maxRecDepth 4000000

namespace BasisFree

/-! ## 1. Encoding -/

def enc (a b c d : Nat) : Nat := a % 7 + 7 * (b % 7) + 49 * (c % 7) + 343 * (d % 7)
def dec (n : Nat) : Nat × Nat × Nat × Nat := (n % 7, n / 7 % 7, n / 49 % 7, n / 343 % 7)

def mulI (m n : Nat) : Nat :=
  let (a, b, c, d) := dec m
  let (p, q, r, s) := dec n
  enc (a*p + b*r) (a*q + b*s) (c*p + d*r) (c*q + d*s)

def detI (m : Nat) : Nat :=
  let (a, b, c, d) := dec m
  (a*d + 7*7 - b*c) % 7

def ident : Nat := enc 1 0 0 1

/-! ## 2. Lines of `F_7^2`, as the eight projective points -/

/-- The eight lines, each given by a representative vector. -/
def lines : List (Nat × Nat) := (List.range 7).map (fun x => (1, x)) ++ [(0, 1)]

/-- Normalize a nonzero vector to the representative of its line. -/
def normLine (v : Nat × Nat) : Nat × Nat :=
  let (x, y) := (v.1 % 7, v.2 % 7)
  if x == 0 then (0, 1)
  else
    let xi := ((List.range 7).filter (fun t => x * t % 7 == 1)).headD 0
    (1, y * xi % 7)

def actL (m : Nat) (v : Nat × Nat) : Nat × Nat :=
  let (a, b, c, d) := dec m
  normLine ((a * v.1 + b * v.2) % 7, (c * v.1 + d * v.2) % 7)

theorem lines_card : lines.length = 8 := by decide

/-! ## 3. An irreducible characteristic polynomial moves every line -/

/-- `X^2 - t X + d` has no root modulo `7`. -/
def irreducibleCharPoly (t d : Nat) : Bool :=
  (List.range 7).all (fun x => (x * x + 7 * 7 - t % 7 * x + d) % 7 != 0)

def traceI (m : Nat) : Nat := let (a, _, _, d) := dec m; (a + d) % 7

/-- The matrices of `GL_2(F_7)` whose characteristic polynomial is irreducible. -/
def irrMats : List Nat :=
  (List.range 2401).filter (fun m => detI m != 0 && irreducibleCharPoly (traceI m) (detI m))

theorem irrMats_card : irrMats.length = 882 := by decide

/-- **No basis is chosen here.**  Every matrix with irreducible characteristic
polynomial moves every line.  In particular the fixed line of a transvection is moved,
so the conjugate transvection has a different fixed line. -/
theorem irreducible_moves_every_line :
    irrMats.all (fun g => lines.all (fun L => actL g L != normLine L)) = true := by decide

/-! ## 4. `SL_2(F_7)` is transitive on ordered pairs of distinct lines -/

def sl2 : List Nat := (List.range 2401).filter (fun m => detI m == 1)

theorem sl2_card : sl2.length = 336 := by decide

/-- The orbit of `(⟨e₁⟩, ⟨e₂⟩)` has `56 = 8 * 7` elements, i.e. is everything. -/
theorem sl2_transitive_on_distinct_pairs :
    ((sl2.map (fun g => (actL g (1, 0), actL g (0, 1)))).eraseDups).length = 56 := by
  decide

/-! ## 5. Two transvections with distinct fixed lines generate -/

def stepOne (gs : List Nat) (S : Nat) : Nat → Nat → Nat
  | 0,     acc => acc
  | i + 1, acc =>
      let acc := if (S >>> i) % 2 == 1
                 then gs.foldl (fun t g => t ||| (1 <<< mulI i g)) acc else acc
      stepOne gs S i acc

def closure (gs : List Nat) (S : Nat) : Nat → Nat
  | 0 => S
  | k + 1 => let T := stepOne gs S 2401 S
             if T == S then S else closure gs T k

def card : Nat → Nat → Nat
  | 0,     _ => 0
  | i + 1, S => (if (S >>> i) % 2 == 1 then 1 else 0) + card i S

/-- Conjugating by `diag(u,1)` sends `[[1,a],[0,1]]` to `[[1,ua],[0,1]]` and
`[[1,0],[b,1]]` to `[[1,0],[u⁻¹b,1]]`, and conjugation carries the subgroup generated by
a pair to the subgroup generated by the conjugated pair.  Taking `u = a⁻¹` therefore
reduces the `36` pairs of section 5 to the `6` with `a = 1`. -/
theorem diagonal_conjugation_normalizes :
    ((List.range 6).map (· + 1)).all (fun a =>
      let u := ((List.range 7).filter (fun t => a * t % 7 == 1)).headD 0
      let D := enc u 0 0 1
      let Di := enc a 0 0 1
      mulI (mulI D (enc 1 a 0 1)) Di == enc 1 1 0 1) = true := by decide

/-- After that normalization the fixed lines are `⟨e₁⟩` and `⟨e₂⟩` and the first
transvection is `[[1,1],[0,1]]`.  Each of the six remaining pairs generates all of
`SL_2(F_7)`. -/
theorem normalized_pairs_generate_1 :
    card 2401 (closure [enc 1 1 0 1, enc 1 0 1 1] (1 <<< ident) 40) = 336 := by decide
theorem normalized_pairs_generate_2 :
    card 2401 (closure [enc 1 1 0 1, enc 1 0 2 1] (1 <<< ident) 40) = 336 := by decide
theorem normalized_pairs_generate_3 :
    card 2401 (closure [enc 1 1 0 1, enc 1 0 3 1] (1 <<< ident) 40) = 336 := by decide
theorem normalized_pairs_generate_4 :
    card 2401 (closure [enc 1 1 0 1, enc 1 0 4 1] (1 <<< ident) 40) = 336 := by decide
theorem normalized_pairs_generate_5 :
    card 2401 (closure [enc 1 1 0 1, enc 1 0 5 1] (1 <<< ident) 40) = 336 := by decide
theorem normalized_pairs_generate_6 :
    card 2401 (closure [enc 1 1 0 1, enc 1 0 6 1] (1 <<< ident) 40) = 336 := by decide

/-! ## 6. Axiom check

The per-declaration axiom dependencies of this file are reported by
`scripts/lean_audit.py`, which runs Lean's print-axioms command on EVERY
declaration the file adds to the environment, not only on the named theorems.
The explicit print-axioms lines that used to stand here covered a self-selected
subset; an axiom report not attributable to a declaration the auditor is
tracking is exactly what the auditor refuses to accept, so they are removed.
-/


end BasisFree
